//Generic Dimension
import 'package:dental_app/screens/details_page.dart';

const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2x = 16.0;
const MARGIN_MEDIUM_3x = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_SMALL = 8.0;
const TEXT_SMALL_2x = 12.0;
const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2x = 16.0;
const TEXT_REGULAR_3x = 20.0;
const TEXT_HEADING = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;

//
const HOMEPAGE_BACKGROUND_BLUE_HEIGHT = 225.0;
const HOMEPAGE_BACKGROUND_TOP_HEIGHT = 300.0;

const HOMEPAGE_BUTTON_HEIGHT = 40.0;
const HOMEPAGE_BUTTON_WIDTH = 90.0;

const HOMEPAGE_SCHEDULE_ITEM_WIDTH = 280.0;
const HOMEPAGE_SCHEDULE_ITEM_HEIGHT = 130.0;

const HOMEPAGE_TIMELIST_WIDTH = 70.0;
const HOMEPAGE_TIME_ITEM_HEIGHT = 32.0;
const HOMEPAGE_EVENT_ITEM_HEIGHT = 80.0;


const VERTICAL_LINE_SECTION_WIDTH = 10.0;

const DETAILS_PAGE_HORIZONTAL_LIST_HEIGHT = 200.0;
const DETAILS_PAGE_CIRCULAR_CONTAINER_HEIGHT = 350.0;
const DETAILS_PAGE_CIRCULAR_CONTAINER_WIDTH = 350.0;

const CLOCK_CANVAS_HEIGHT = 330.0;
const CLOCK_CANVAS_WIDTH = 330.0;
const CLOCK_INNER_CIRCLE_RADIUS = 75.0;
const CLOCK_OUTTER_CIRCLE_RADIUS = 150.0;
const CLOCK_DOTTED_CIRCLE_RADIUS = 112.5;